plugins {
    id 'java'
    id 'groovy'
}

group = 'csci.ooad'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'ch.qos.logback:logback-classic:1.4.14'
    implementation 'commons-cli:commons-cli:1.6.0'


    // Maze display
    implementation files('libs/csci4448.gameLayout-2.0.0.jar')

    // library to speak strings: Free Text-To-Speech
    implementation 'net.sf.sociaal:freetts:1.2.2'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // BDD testing libraries
    testImplementation 'io.cucumber:cucumber-picocontainer:7.8.0'
    testImplementation 'io.cucumber:cucumber-java:6.10.4'
    testImplementation 'io.cucumber:cucumber-groovy:6.10.4'
    testImplementation 'org.apache.groovy:groovy:4.0.23'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17 // or VERSION_21
    targetCompatibility = JavaVersion.VERSION_17 // or VERSION_21
}


test {
    useJUnitPlatform()
}

configurations {
    cucumberRuntime {
        extendsFrom testImplementation
    }
}

tasks.register('cucumberCli') {
    dependsOn assemble, testClasses
    doLast {
        javaexec {
            mainClass = "io.cucumber.core.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = [
                    '--plugin', 'pretty', 'html:bddReports',
                    '--snippets', 'camelcase',
                    '--plugin', 'html:target/cucumber-report.html',
                    '--glue', 'csci.ooad.polymorphia.stepdefs',
                    'src/test/resources/features'
            ]
        }
    }
}